// Authoritative unit list — 150 units
// Source: units.json + trainer_unit_status.csv
// Do not edit manually — regenerate from source files

export const INDUSTRIES = [
  { code: "AMP", name: "Australian Meat Processing" },
  { code: "BSB", name: "Business Services" },
  { code: "CHC", name: "Community Services" },
  { code: "FBP", name: "Food, Beverage and Pharmaceutical" },
  { code: "HLT", name: "Health" },
  { code: "MSL", name: "Laboratory Operations" },
  { code: "MSM", name: "Manufacturing" },
  { code: "RII", name: "Resources and Infrastructure" },
  { code: "TAE", name: "Training and Education" },
  { code: "TLI", name: "Transport and Logistics" },
];

export const UNITS = [
  {
    code: "AMPCOR203",
    title: "Comply with Quality Assurance and HACCP requirements",
    industry: "AMP",
    industryName: "Australian Meat Processing",
    question: "I have experience, skills and knowledge required to apply Quality Assurance (QA) procedures and Hazard Analysis and Critical Control Points (HACCP) requirements in a meat establishment..",
    elements: [],
  },
  {
    code: "BSBCMM211",
    title: "Apply communication skills",
    industry: "BSB",
    industryName: "Business Services",
    question: "I have experience, skills and knowledge required to apply basic communication skills in the workplace, including identifying, gathering and conveying information along with completing assigned written information..",
    elements: [],
  },
  {
    code: "BSBLDR413",
    title: "Lead effective workplace relationships",
    industry: "BSB",
    industryName: "Business Services",
    question: "I have experience, skills and knowledge required to use leadership to promote team cohesion..",
    elements: [],
  },
  {
    code: "BSBLDR414",
    title: "Lead team effectiveness",
    industry: "BSB",
    industryName: "Business Services",
    question: "I have experience, skills and knowledge required to lead the performance of a team and to develop team cohesion.",
    elements: [],
  },
  {
    code: "BSBMED301",
    title: "Interpret and apply medical terminology appropriately",
    industry: "BSB",
    industryName: "Business Services",
    question:
      "I have experience, skills and knowledge required to understand and respond to instructions; to carry out routine tasks and communicate with a range of internal/external clients in a medical environment; as well as use appropriate medical terminology..",
    elements: [],
  },
  {
    code: "BSBOPS203",
    title: "Deliver a service to customers",
    industry: "BSB",
    industryName: "Business Services",
    question:
      "I have experience, skills and knowledge required to deliver aspects of customer service at an introductory level. It includes creating a relationship with customers, identifying their needs, delivering services or products, and processing customer feedback..",
    elements: [],
  },
  {
    code: "BSBOPS305",
    title: "Process customer complaints",
    industry: "BSB",
    industryName: "Business Services",
    question: "I have experience, skills and knowledge required to handle complaints from customers..",
    elements: [],
  },
  {
    code: "BSBTEC201",
    title: "Use business software applications",
    industry: "BSB",
    industryName: "Business Services",
    question: "I have experience, skills and knowledge required to select and use software and organise electronic information and data..",
    elements: [],
  },
  {
    code: "CHCCCS020",
    title: "Respond effectively to behaviours of concern",
    industry: "CHC",
    industryName: "Community Services",
    question: "I have experience, skills and knowledge required to respond effectively to behaviours of concern of people. Skills are associated with handling difficult incidents rather than managing ongoing behaviour difficulties..",
    elements: [],
  },
  {
    code: "CHCCCS037",
    title: "Visit client residence",
    industry: "CHC",
    industryName: "Community Services",
    question: "I have experience, skills and knowledge required to make visits to clients to assess needs and/or deliver services in their place of residence..",
    elements: [],
  },
  {
    code: "CHCCOM001",
    title: "Provide first point of contact",
    industry: "CHC",
    industryName: "Community Services",
    question: "I have experience, skills and knowledge required to greet clients and exchange routine information, to prioritise the individual\u2019s needs, and to respond to immediate needs..",
    elements: [],
  },
  {
    code: "CHCCOM005",
    title: "Communicate and work in health or community services",
    industry: "CHC",
    industryName: "Community Services",
    question: "I have experience, skills and knowledge required to communicate effectively with clients, colleagues, management and other industry providers..",
    elements: [],
  },
  {
    code: "CHCDIV001",
    title: "Work with diverse people",
    industry: "CHC",
    industryName: "Community Services",
    question: "I have experience, skills and knowledge required to work respectfully with people from diverse social and cultural groups and situations, including Aboriginal and/or Torres Strait Islander people..",
    elements: [],
  },
  {
    code: "CHCDIV002",
    title: "Promote Aboriginal and/or Torres Strait Islander cultural safety",
    industry: "CHC",
    industryName: "Community Services",
    question:
      "I have experience, skills and knowledge required to identify Aboriginal and/or Torres Strait Islander cultural safety issues in the workplace, model cultural safety in own work practice, and develop strategies to enhance cultural safety..",
    elements: [],
  },
  {
    code: "CHCYTH013",
    title: "Engage respectfully with young people",
    industry: "CHC",
    industryName: "Community Services",
    question: "I have experience, skills and knowledge required to communicate effectively with children and young people in work roles with a specific focus on young people..",
    elements: [],
  },
  {
    code: "FBPFST4004",
    title: "Perform microbiological procedures in the food industry",
    industry: "FBP",
    industryName: "Food, Beverage and Pharmaceutical",
    question: "I have experience, skills and knowledge required to perform on-site microbiological procedures in the food industry..",
    elements: [],
  },
  {
    code: "FBPFST5005",
    title: "Examine the biochemical properties of food",
    industry: "FBP",
    industryName: "Food, Beverage and Pharmaceutical",
    question: "I have experience, skills and knowledge required to examine biochemical substances and reactions and apply knowledge to food product development and processing..",
    elements: [],
  },
  {
    code: "FBPFSY3002",
    title: "Participate in a HACCP team",
    industry: "FBP",
    industryName: "Food, Beverage and Pharmaceutical",
    question: "I have experience, skills and knowledge required to participate in the development and review of a hazard analysis critical control point (HACCP)-based food safety program..",
    elements: [],
  },
  {
    code: "FBPFSY3003",
    title: "Monitor the implementation of food safety and quality programs",
    industry: "FBP",
    industryName: "Food, Beverage and Pharmaceutical",
    question: "I have experience, skills and knowledge required to provide a leadership role in supporting day-to-day implementation of the food safety (including food allergen management) and quality programs and procedures in a work area..",
    elements: [],
  },
  {
    code: "FBPFSY4001",
    title: "Supervise and maintain a food safety plan",
    industry: "FBP",
    industryName: "Food, Beverage and Pharmaceutical",
    question: "I have experience, skills and knowledge required to maintain and implement a hazard analysis critical control point (HACCP) based food safety plan..",
    elements: [],
  },
  {
    code: "FBPFSY5001",
    title: "Develop a HACCP-based food safety plan",
    industry: "FBP",
    industryName: "Food, Beverage and Pharmaceutical",
    question: "I have experience, skills and knowledge required to develop a hazard analysis critical control point (HACCP)-based food safety plan and to oversee its implementation and monitoring..",
    elements: [],
  },
  {
    code: "FBPSUG2024",
    title: "Perform standard tests on cane samples",
    industry: "FBP",
    industryName: "Food, Beverage and Pharmaceutical",
    question: "I have experience, skills and knowledge required to perform standard tests on cane samples for routine factory control..",
    elements: [],
  },
  {
    code: "FBPSUG3007",
    title: "Perform factory control tests",
    industry: "FBP",
    industryName: "Food, Beverage and Pharmaceutical",
    question: "I have experience, skills and knowledge required to perform tests for factory control..",
    elements: [],
  },
  {
    code: "FBPTEC4009",
    title: "Identify the physical and chemical properties of materials, food and related products",
    industry: "FBP",
    industryName: "Food, Beverage and Pharmaceutical",
    question: "I have experience, skills and knowledge required to identify the physical and chemical properties of materials, foods and related products within a production environment..",
    elements: [],
  },
  {
    code: "HLTAAP001",
    title: "Recognise healthy body systems",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to work with basic information about the human body and to recognise and promote ways to maintain healthy functioning of the body..",
    elements: [],
  },
  {
    code: "HLTAID009",
    title: "Provide cardiopulmonary resuscitation",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to perform cardiopulmonary resuscitation (CPR) in line with the Australian Resuscitation Council (ARC) guidelines.",
    elements: [],
  },
  {
    code: "HLTAID011",
    title: "Provide first aid",
    industry: "HLT",
    industryName: "Health",
    question:
      "I have experience, skills and knowledge required to provide a first aid response to a casualty in line with first aid guidelines determined by the Australian Resuscitation Council (ARC) and other Australian national peak clinical bodies..",
    elements: [],
  },
  {
    code: "HLTCAR004",
    title: "Perform electrocardiography (ECG)",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to prepare for and conduct electrocardiography (ECG) procedures, producing traces that are suitable for diagnostic purposes. It does not include interpretation of the ECG..",
    elements: [],
  },
  {
    code: "HLTCAR005",
    title: "Perform holter monitoring",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to attach a holter monitor and produce a diagnostic trace for submission to the requesting medical officer..",
    elements: [],
  },
  {
    code: "HLTHPS001",
    title: "Take clinical measurements",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to prepare for, obtain and record simple clinical measurements..",
    elements: [],
  },
  {
    code: "HLTHPS002",
    title: "Support health professional in the delivery of care",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to complete preparation, general assistance and follow up tasks that support health professionals in the delivery of care to clients..",
    elements: [],
  },
  {
    code: "HLTHPS011",
    title: "Measure spirometry",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to prepare an individual for spirometry, complete the spirometry test and to provide a report as an aid to the diagnosis and management of ventilatory impairment..",
    elements: [],
  },
  {
    code: "HLTINF006",
    title: "Apply basic principles and practices of infection prevention and control",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to apply basic infection prevention and control principles in work settings including implementing standard and transmission-based precautions and responding to risks..",
    elements: [],
  },
  {
    code: "HLTPAT008",
    title: "Identify and respond to clinical risks in pathology collection",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to recognise individual risk factors, identify emergency situations, and provide emergency or first aid response to individual reactions associated with pathology specimen collection..",
    elements: [],
  },
  {
    code: "HLTPAT009",
    title: "Collect pathology specimens other than blood",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to confirm collection requirements, prepare client and equipment, and make routine pathology specimen collections..",
    elements: [],
  },
  {
    code: "HLTPAT010",
    title: "Collect specimens for drugs of abuse testing",
    industry: "HLT",
    industryName: "Health",
    question:
      "I have experience, skills and knowledge required to confirm collection requirements, prepare individual and equipment and collect specimens via urine and/or oral and breath testing following the special procedures that apply for drugs of abuse testing..",
    elements: [],
  },
  {
    code: "HLTPAT011",
    title: "Receive, prepare and dispatch pathology specimens",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to receive specimens, complete the administrative process to prepare samples for pathology testing, and dispatch specimens..",
    elements: [],
  },
  {
    code: "HLTPAT012",
    title: "Perform capillary blood collections",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to confirm collection requirements, prepare client and equipment, and collect capillary blood using specific collection criteria, techniques and equipment..",
    elements: [],
  },
  {
    code: "HLTPAT013",
    title: "Collect venous blood from children 0 to 5 years",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to prepare, collect and complete venous blood specimens from children from 0 to 5 years..",
    elements: [],
  },
  {
    code: "HLTPAT014",
    title: "Perform venous blood collection",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to confirm venous blood collection requirements, prepare individual and equipment, and perform routine venous blood collections..",
    elements: [],
  },
  {
    code: "HLTWHS001",
    title: "Participate in workplace health and safety",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to participate in safe work practices to ensure their own health and safety, and that of others..",
    elements: [],
  },
  {
    code: "HLTWHS006",
    title: "Manage personal stressors in the work environment",
    industry: "HLT",
    industryName: "Health",
    question: "I have experience, skills and knowledge required to maintain health and wellbeing by preventing and managing personal stress..",
    elements: [],
  },
  {
    code: "MSL904003",
    title: "Perform standard calibrations",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to calibrate test and measurement equipment in accordance with standard calibration procedures and documented test methods..",
    elements: [],
  },
  {
    code: "MSL905004",
    title: "Perform non-standard calibrations",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to recognise non-conforming calibration work, research and select the most appropriate test method or calibration procedure for a given measurement request, and then conduct the calibration..",
    elements: [],
  },
  {
    code: "MSL905005",
    title: "Create or modify calibration procedures",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to create or modify calibration procedures in response to the introduction of alternative/new equipment, changing test circumstances, activities involved in research and development trials or to meet client needs..",
    elements: [],
  },
  {
    code: "MSL912002",
    title: "Work within a laboratory or field workplace",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to work effectively in a laboratory/field workplace..",
    elements: [],
  },
  {
    code: "MSL913004",
    title: "Plan and conduct laboratory/field work",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to plan and complete tasks individually or in a team context..",
    elements: [],
  },
  {
    code: "MSL914002",
    title: "Prepare practical science classes and demonstrations",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to manage the day-to-day running of science teaching laboratories and the preparation of practical experiments, demonstrations and field trips..",
    elements: [],
  },
  {
    code: "MSL915003",
    title: "Provide information to customers",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to respond to both internal and external inquiries of a specialised technical nature..",
    elements: [],
  },
  {
    code: "MSL915004",
    title: "Schedule laboratory work for a small team",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to schedule laboratory work for a small team to meet operational requirements..",
    elements: [],
  },
  {
    code: "MSL916011",
    title: "Develop and maintain laboratory documentation",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to develop and maintain relevant documentation in response to identified information requirements or changes in laboratory policy or external accreditation requirements..",
    elements: [],
  },
  {
    code: "MSL916012",
    title: "Manage and develop teams",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to develop and empower team members through motivating, mentoring, coaching and promoting team cohesion to achieve planned outcomes..",
    elements: [],
  },
  {
    code: "MSL916013",
    title: "Supervise laboratory operations in work or functional area",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to monitor and direct work practices, coordinate and support personnel and manage and optimise resources within the laboratory..",
    elements: [],
  },
  {
    code: "MSL916014",
    title: "Maintain compliance in work or functional area",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to take responsibility for the day-to-day operation of the work or functional area and its compliance with legislation and licensing, registration, ethical or accreditation requirements..",
    elements: [],
  },
  {
    code: "MSL916015",
    title: "Manage complex projects",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to interpret complex project briefs, determine project methodologies and resource requirements, establish project plans, manage projects to successful conclusions and evaluate project outcomes..",
    elements: [],
  },
  {
    code: "MSL922002",
    title: "Record and present data",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to record and store data, perform simple calculations of scientific quantities and present information in tables and graphs..",
    elements: [],
  },
  {
    code: "MSL924005",
    title: "Process and interpret data",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to retrieve data, evaluate formulae, perform scientific calculations, present and interpret information in tables and graphs and keep accurate records..",
    elements: [],
  },
  {
    code: "MSL924006",
    title: "Use laboratory application software",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to use enterprise laboratory-specific software such as laboratory information management systems, quality information management systems, laboratory instrument software, middleware and quality control data management systems..",
    elements: [],
  },
  {
    code: "MSL925005",
    title: "Analyse measurements and estimate uncertainties",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to use statistical analysis to estimate and report measurement uncertainty in accordance with the ISO Guide to the Expression of Uncertainty in Measurement (or its replacement Standard)..",
    elements: [],
  },
  {
    code: "MSL925006",
    title: "Analyse data and report results",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to perform scientific calculations, analyse trends and uncertainty in data and report results within the required timeframe..",
    elements: [],
  },
  {
    code: "MSL933005",
    title: "Maintain the laboratory/field workplace fit for purpose",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to clean laboratory work surfaces, clean and store laboratory equipment and monitor laboratory stocks under direct supervision..",
    elements: [],
  },
  {
    code: "MSL933007",
    title: "Apply critical control point requirements",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to monitor critical, quality and regulatory control points related to a person's work responsibilities..",
    elements: [],
  },
  {
    code: "MSL933008",
    title: "Perform calibration checks on equipment and assist with its maintenance",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to perform set-up, pre-use and in-house calibration/validation checks on laboratory equipment and assist with laboratory equipment maintenance..",
    elements: [],
  },
  {
    code: "MSL933009",
    title: "Contribute to the achievement of quality objectives",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to apply quality principles to laboratory or field work to achieve quality outcomes..",
    elements: [],
  },
  {
    code: "MSL934008",
    title: "Maintain instruments and equipment",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to check the serviceability and calibration of laboratory or field instruments and equipment and perform routine maintenance, such as cleaning and replacement of consumables and minor components..",
    elements: [],
  },
  {
    code: "MSL934009",
    title: "Apply quality system and continuous improvement processes",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to use quality laboratory practice and effectively participate in quality improvement teams..",
    elements: [],
  },
  {
    code: "MSL934010",
    title: "Maintain and control stocks",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to order, maintain and control the use of laboratory materials and/or equipment in the work area..",
    elements: [],
  },
  {
    code: "MSL935005",
    title: "Authorise the issue of test results",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to critically assess the accuracy of data and validity of test results prior to formally authorising their release to the client..",
    elements: [],
  },
  {
    code: "MSL935006",
    title: "Assist in the maintenance of reference materials",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to assist in the maintenance of reference materials that can be used in tests and the identification of new specimens as part of quality control of laboratory procedures..",
    elements: [],
  },
  {
    code: "MSL935008",
    title: "Monitor the quality of test results and data",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to analyse a series of test results and data to detect potential or actual non-conformances, assess their significance and recommend preventative or corrective actions..",
    elements: [],
  },
  {
    code: "MSL936005",
    title: "Maintain quality system and continuous improvement processes within work or functional area",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to take responsibility for the day-to-day operation of the work or functional area and ensure that quality system requirements are met and continuous improvements are initiated..",
    elements: [],
  },
  {
    code: "MSL936006",
    title: "Conduct an internal audit of the quality system",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to prepare for, conduct and document an internal audit of aspects of the laboratory\u2019s quality system..",
    elements: [],
  },
  {
    code: "MSL943003",
    title: "Work safely with instruments that emit ionising radiation",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to safely store, transport and operate instruments that emit ionising radiation following established safe work practices and in accordance with laboratory procedures and licensing requirements..",
    elements: [],
  },
  {
    code: "MSL943004",
    title: "Participate in laboratory or field workplace safety",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to follow work health and safety (WHS) policies and procedures, deal with the identification and control of hazards, work safely at all times, follow emergency response procedures and contribute to the maintenance of workplace safety..",
    elements: [],
  },
  {
    code: "MSL944002",
    title: "Maintain laboratory or field workplace safety",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to monitor and maintain work health and safety (WHS) within a work area where the person has supervisory responsibility for others..",
    elements: [],
  },
  {
    code: "MSL946003",
    title: "Implement and monitor WHS and environmental management systems",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to implement and monitor the work health and safety (WHS) and environmental management systems for a work group or laboratory..",
    elements: [],
  },
  {
    code: "MSL952003",
    title: "Collect routine site samples",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to collect samples at field or production sites using specified equipment and workplace procedures..",
    elements: [],
  },
  {
    code: "MSL952004",
    title: "Handle and transport samples or equipment",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to pick up and transport samples or test/calibration equipment in a way that ensures the integrity of subsequent test results..",
    elements: [],
  },
  {
    code: "MSL953004",
    title: "Operate a robotic sample preparation system",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to operate a robotic sample preparation system to ensure efficient throughput of samples without sacrificing quality or safety..",
    elements: [],
  },
  {
    code: "MSL953005",
    title: "Receive and prepare samples for testing",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to log samples, check sample documentation, and schedule and prepare samples for testing in accordance with workplace procedures..",
    elements: [],
  },
  {
    code: "MSL954005",
    title: "Prepare mineral samples for analysis",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to reduce given mineral samples to representative client samples and analytical portions that meet client requirements for analysis..",
    elements: [],
  },
  {
    code: "MSL954006",
    title: "Relate anatomical and physiological features to laboratory samples",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to recognise and interpret different types of biological test samples to direct the specimen to the appropriate laboratory for testing..",
    elements: [],
  },
  {
    code: "MSL954007",
    title: "Obtain representative samples in accordance with sampling plan",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to obtain a range of samples that are representative of the source material and to prepare the samples for testing..",
    elements: [],
  },
  {
    code: "MSL972002",
    title: "Take routine site measurements",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to take direct measurements on site using workplace procedures..",
    elements: [],
  },
  {
    code: "MSL973015",
    title: "Prepare culture media",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to prepare culture media which is free of contamination to facilitate optimal growth of organisms and cells..",
    elements: [],
  },
  {
    code: "MSL973017",
    title: "Assist with fieldwork",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to perform tasks associated with the organisation of fieldwork and field surveys..",
    elements: [],
  },
  {
    code: "MSL973018",
    title: "Prepare trial batches for evaluation",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to prepare trial batches of materials for evaluation..",
    elements: [],
  },
  {
    code: "MSL973021",
    title: "Conduct field-based acceptance tests for construction materials",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to conduct in situ tests to confirm the acceptability of raw or manufactured, construction materials prior to or after their use..",
    elements: [],
  },
  {
    code: "MSL973022",
    title: "Conduct laboratory-based acceptance tests for construction materials",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to conduct laboratory tests to confirm the acceptability of raw and/or manufactured construction materials.",
    elements: [],
  },
  {
    code: "MSL973023",
    title: "Perform fire pouring techniques",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to follow standard procedures for extracting precious metals from their host matrices in readiness for analysis..",
    elements: [],
  },
  {
    code: "MSL973024",
    title: "Perform site investigation activities",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to prepare for and conduct activities, such as excavations, sampling and testing, as part of a site investigation team..",
    elements: [],
  },
  {
    code: "MSL973025",
    title: "Perform basic tests",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to prepare samples and perform tests and measurements using standard methods with access to readily available advice from supervisors..",
    elements: [],
  },
  {
    code: "MSL973026",
    title: "Prepare working solutions",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to prepare working solutions and to check that existing stocks of solutions are suitable for use. Working solutions include those required to perform laboratory tests..",
    elements: [],
  },
  {
    code: "MSL973027",
    title: "Perform techniques that prevent cross-contamination",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to perform techniques that prevent cross-contamination to maintain the integrity of both the sample source, and the sample and protect people and the environment..",
    elements: [],
  },
  {
    code: "MSL973028",
    title: "Perform microscopic examination",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to set up a light microscope for optimum resolution, to prepare routine samples and to observe, identify and report sample characteristics..",
    elements: [],
  },
  {
    code: "MSL973029",
    title: "Perform histological procedures",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to perform straightforward histological procedures involving processing and sectioning (by rotary microtome) of plant and/or animal tissues in paraffin wax..",
    elements: [],
  },
  {
    code: "MSL974016",
    title: "Perform physical and mechanical tests",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to interpret physical and mechanical test requirements, prepare samples, conduct pre-use and calibration checks on equipment and perform routine physical tests..",
    elements: [],
  },
  {
    code: "MSL974018",
    title: "Conduct geotechnical site investigations",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to prepare for and conduct and conclude site activities, such as excavations, sampling and testing as part of a geotechnical investigation team..",
    elements: [],
  },
  {
    code: "MSL974022",
    title: "Undertake environmental field-based monitoring",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to organise and undertake field monitoring programs that are primarily focused on the determination of physical and chemical parameters and/or observation and documentation of biological/ecological systems..",
    elements: [],
  },
  {
    code: "MSL974023",
    title: "Capture and manage scientific images",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to capture accurate and reproducible images of scientific (environmental, medical and technical) subjects using a scientific approach and workplace procedures/protocols to ensure the integrity of the image..",
    elements: [],
  },
  {
    code: "MSL974026",
    title: "Perform tests to determine the properties of construction materials",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to conduct multi-stage tests to determine the properties of raw and/or manufactured construction materials..",
    elements: [],
  },
  {
    code: "MSL974028",
    title: "Classify soils",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to classify soils for geotechnical and civil construction purposes using the symbols and descriptors specified in the Australian Standard for Geotechnical Site Investigations (AS 1726-2017 Geotechnical site investigations, or its replacement)..",
    elements: [],
  },
  {
    code: "MSL974029",
    title: "Operate an automated mineral analysis system",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to operate a computer-controlled robotic system for the specialised analysis of minerals, such as iron ore..",
    elements: [],
  },
  {
    code: "MSL974031",
    title: "Prepare, standardise and use solutions",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to prepare, standardise and monitor the quality of solutions..",
    elements: [],
  },
  {
    code: "MSL974032",
    title: "Perform chemical tests and procedures",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to interpret chemical test requirements, prepare samples, conduct pre-use and calibration checks on equipment and perform routine chemical tests..",
    elements: [],
  },
  {
    code: "MSL974033",
    title: "Perform food tests",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to interpret food test requirements, prepare samples, conduct pre-use and calibration checks on equipment, and perform routine testing of raw food materials, in-process materials and final products..",
    elements: [],
  },
  {
    code: "MSL974034",
    title: "Perform biological procedures",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to interpret work requirements, prepare samples, and perform routine biological procedures..",
    elements: [],
  },
  {
    code: "MSL974035",
    title: "Prepare tissue and cell cultures",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to prepare primary tissue cultures for applications, such as maintenance of animal cell lines and propagation of plants by tissue culture, and basic subculture procedures..",
    elements: [],
  },
  {
    code: "MSL974036",
    title: "Process body fluid specimens using a point of care testing device",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to complete pre-analytics, analyse body fluid specimens, record results and maintain a point of care testing (PoCT) device..",
    elements: [],
  },
  {
    code: "MSL974037",
    title: "Triage and allocate tissue specimens",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to triage and allocate tissue specimens for transfer or surgical cut-up..",
    elements: [],
  },
  {
    code: "MSL974038",
    title: "Use techniques to complete simple tissue specimen transfers",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to process and transfer tissue specimens that require no selection or cutting..",
    elements: [],
  },
  {
    code: "MSL975032",
    title: "Provide input to production trials",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to work closely with production personnel to conduct a routine trial to adjust formulations or develop products and processes following preliminary laboratory work..",
    elements: [],
  },
  {
    code: "MSL975038",
    title: "Conduct sensory analysis",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to set up and coordinate sensory analysis and assess the results obtained from a routine sensory analysis..",
    elements: [],
  },
  {
    code: "MSL975041",
    title: "Perform fire assay techniques",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to safely extract a range of precious metals from their host matrices in readiness for analysis..",
    elements: [],
  },
  {
    code: "MSL975042",
    title: "Design and supervise complex environmental field surveys",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to design and supervise complex field surveys for a wide range of environmental systems..",
    elements: [],
  },
  {
    code: "MSL975043",
    title: "Prepare animal and plant material for display",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to perform a range of techniques to collect and preserve animals and plant material for both public and scientific research display..",
    elements: [],
  },
  {
    code: "MSL975044",
    title: "Perform complex tests to measure engineering properties of materials",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to prepare test specimens and perform multi-stage mechanical tests on them..",
    elements: [],
  },
  {
    code: "MSL975051",
    title: "Supervise geotechnical site investigations",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to supervise and direct geotechnical site investigations based on observation and testing..",
    elements: [],
  },
  {
    code: "MSL975052",
    title: "Locate, record and collect forensic samples",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to locate, record and collect evidence or samples that will be used for forensic examination or testing..",
    elements: [],
  },
  {
    code: "MSL975055",
    title: "Classify building sites",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to classify building sites, including residential, light industrial, commercial and institutional structures for the purpose of providing guidance for the design of footing systems..",
    elements: [],
  },
  {
    code: "MSL975056",
    title: "Perform advanced histological techniques",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to perform procedures associated with embedding tissue and performing microtomy on those tissues in preparation for staining for examination of tissue structure and abnormalities by pathologists and scientists to assist with disease diagnosis..",
    elements: [],
  },
  {
    code: "MSL975057",
    title: "Perform histological tests",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to perform tests and procedures associated with processing and staining tissues for examination of tissue structure and abnormalities by pathologists and scientists to assist with disease diagnosis..",
    elements: [],
  },
  {
    code: "MSL975058",
    title: "Perform immunohaematological tests",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to perform routine tests and procedures that are part of the requirements of pre- and post-blood transfusion practice..",
    elements: [],
  },
  {
    code: "MSL975059",
    title: "Supervise sampling, inspections and testing at construction sites",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to supervise and direct the placement of materials, such as soil, concrete and asphalt, at a construction site..",
    elements: [],
  },
  {
    code: "MSL975060",
    title: "Perform tissue or cell culture techniques",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to prepare, maintain and preserve cells and cell lines for a variety of applications, such as large-scale culture, production of monoclonal antibodies, production of viral vaccines and amniocentesis studies..",
    elements: [],
  },
  {
    code: "MSL975061",
    title: "Perform molecular biology tests and procedures",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to isolate, purify, verify and manipulate biomolecules and their products..",
    elements: [],
  },
  {
    code: "MSL975062",
    title: "Perform microbiological tests",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to contribute to the culture, isolation and identification of microorganisms, such as bacteria, fungi, viruses, protozoans, algae and parasites, in order to investigate the physiology and pathology of animals, monitor the natural environment, and to assist in the production of foods, pharmaceutical goods and other manufactured materials..",
    elements: [],
  },
  {
    code: "MSL975063",
    title: "Perform haematological tests",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to determine levels, function, activity and interactions of cellular and plasma components of blood, using tests and procedures identified with the discipline of laboratory haematology..",
    elements: [],
  },
  {
    code: "MSL975064",
    title: "Perform chemical pathology tests",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to perform tests and procedures associated with the detection and monitoring of tissue and bodily fluid responses to normal physiological processes and disease through the identification and quantifying of chemical components..",
    elements: [],
  },
  {
    code: "MSL975065",
    title: "Apply electrophoretic techniques",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to analyse samples using electrophoretic techniques.",
    elements: [],
  },
  {
    code: "MSL975066",
    title: "Apply routine chromatographic techniques",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to analyse samples using routine chromatographic techniques..",
    elements: [],
  },
  {
    code: "MSL975067",
    title: "Perform complex tests to measure chemical properties of materials",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to isolate analytes from complex matrices and perform multi-staged and multi-component analyses on them..",
    elements: [],
  },
  {
    code: "MSL975068",
    title: "Apply complex instrumental techniques",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to analyse samples using specialised analytical instruments that require highly-developed technical skills to operate effectively..",
    elements: [],
  },
  {
    code: "MSL975069",
    title: "Apply routine spectrometric techniques",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to analyse samples using routine spectrometric techniques..",
    elements: [],
  },
  {
    code: "MSL975070",
    title: "Apply routine electrometric techniques",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to analyse samples using routine electrometric techniques..",
    elements: [],
  },
  {
    code: "MSL975071",
    title: "Perform food analyses",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to analyse the nutrient and ingredient composition of foods and the identification and quantification of both chemical and biological contaminants within raw and processed foods..",
    elements: [],
  },
  {
    code: "MSL975072",
    title: "Use surgical cut techniques for non-complex tissue specimens",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to prepare for and complete surgical cut-up of non-complex specimens as defined by the National Pathology Accreditation Advisory Council (NPAAC)..",
    elements: [],
  },
  {
    code: "MSL975073",
    title: "Perform laboratory-based ecological techniques",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to participate in laboratory investigations involving animals, plants and related environmental parameters..",
    elements: [],
  },
  {
    code: "MSL976006",
    title: "Evaluate and select appropriate test methods and/or procedures",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to evaluate and select test methods and/or procedures that are relevant to the current and evolving scope of the laboratory\u2019s operations..",
    elements: [],
  },
  {
    code: "MSL977009",
    title: "Validate test methods",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to validate test methods following defined protocols to ensure that they are based on sound scientific principles and are fit for the purpose for which they are to be used..",
    elements: [],
  },
  {
    code: "MSL977010",
    title: "Contribute to the development of products or applications",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question:
      "I have experience, skills and knowledge required to evaluate a product or application brief from a technical perspective and to contribute to the formulation and development of products or applications to meet the brief requirements..",
    elements: [],
  },
  {
    code: "MSL977011",
    title: "Troubleshoot equipment and/or production processes",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to apply technical, instrumental and equipment knowledge and skills to troubleshoot testing equipment and/or testing issues related to production processes..",
    elements: [],
  },
  {
    code: "MSL977012",
    title: "Develop or adapt analyses and procedures",
    industry: "MSL",
    industryName: "Laboratory Operations",
    question: "I have experience, skills and knowledge required to develop or adapt analyses, including methods and procedures, to meet workplace and/or regulatory requirements..",
    elements: [],
  },
  {
    code: "MSMENV272",
    title: "Participate in environmentally sustainable work practices",
    industry: "MSM",
    industryName: "Manufacturing",
    question: "I have experience, skills and knowledge required to comply with environmental regulations, identify environment issues and minimise the risks of negative impact on work and carry out improvements in own work area..",
    elements: [],
  },
  {
    code: "MSMENV472",
    title: "Implement and monitor environmentally sustainable work practices",
    industry: "MSM",
    industryName: "Manufacturing",
    question: "I have experience, skills and knowledge required to effectively analyse the workplace in relation to environmentally sustainable work practices, and to implement improvements and monitor their effectiveness..",
    elements: [],
  },
  {
    code: "MSMENV672",
    title: "Develop workplace policy and procedures for environmental sustainability",
    industry: "MSM",
    industryName: "Manufacturing",
    question: "I have experience, skills and knowledge required to develop and implement a workplace sustainability policy, including the modification of the policy to suit changed circumstances..",
    elements: [],
  },
  {
    code: "MSMSUP301",
    title: "Apply HACCP to the workplace",
    industry: "MSM",
    industryName: "Manufacturing",
    question:
      "I have experience, skills and knowledge required to apply the hazard analysis and critical control point (HACCP) principles to the manufacture of products to be used in contact with food, beverages, pharmaceuticals or similar situations..",
    elements: [],
  },
  {
    code: "RIISTD401",
    title: "Monitor quarry laboratory operations and the quality of results",
    industry: "RII",
    industryName: "Resources and Infrastructure",
    question: "I have experience, skills and knowledge required to monitor laboratory operations and the quality of results in the extractive industry..",
    elements: [],
  },
  {
    code: "TAEDEL311",
    title: "Provide work skill instruction",
    industry: "TAE",
    industryName: "Training and Education",
    question:
      "I have experience, skills and knowledge required to conduct individual and small group work skill instruction using existing support materials and demonstration of work skills as a training strategy; and assess the success of training and one\u2019s own training performance.",
    elements: [],
  },
  {
    code: "TLIF3091",
    title: "Apply awareness of dangerous goods and hazardous materials requirements",
    industry: "TLI",
    industryName: "Transport and Logistics",
    question: "I have experience, skills and knowledge required to identify and apply an awareness of hazardous substances and dangerous goods requirements..",
    elements: [],
  },
];
