export const UNITS = [
  // ─── AMP — Australian Meat Processing ───
  {
    code: "AMPCOR203",
    title: "Comply with Quality Assurance and HACCP requirements",
    industry: "AMP",
    industryName: "Australian Meat Processing",
    desc: "Apply QA procedures and Hazard Analysis and Critical Control Points requirements in a meat establishment.",
    elements: ["Identify hazards and control points", "Identify elements of the QA system", "Follow requirements of a HACCP-based QA system", "Inspect own work"],
  },

  // ─── BSB — Business Services ───
  {
    code: "BSBCMM211",
    title: "Apply communication skills",
    industry: "BSB",
    industryName: "Business Services",
    desc: "Apply basic communication skills in the workplace including identifying, gathering and conveying information and completing assigned written information.",
    elements: ["Identify workplace communication procedures", "Communicate in the workplace", "Draft written information"],
  },
  {
    code: "BSBLDR413",
    title: "Lead effective workplace relationships",
    industry: "BSB",
    industryName: "Business Services",
    desc: "Use leadership to promote team cohesion.",
    elements: ["Prepare to lead workplace relationships", "Lead workplace relationships", "Review leadership"],
  },
  {
    code: "BSBLDR414",
    title: "Lead team effectiveness",
    industry: "BSB",
    industryName: "Business Services",
    desc: "Lead the performance of a team and develop team cohesion.",
    elements: ["Plan team outcomes", "Promote team cohesion", "Supervise team performance", "Liaise with management"],
  },
  {
    code: "BSBMED301",
    title: "Interpret and apply medical terminology appropriately",
    industry: "BSB",
    industryName: "Business Services",
    desc: "Understand and respond to instructions and communicate with a range of internal and external clients using appropriate medical terminology.",
    elements: ["Respond appropriately to instructions containing medical terminology", "Carry out routine tasks", "Use appropriate medical terminology in oral and written communication"],
  },
  {
    code: "BSBOPS203",
    title: "Deliver a service to customers",
    industry: "BSB",
    industryName: "Business Services",
    desc: "Deliver aspects of customer service at an introductory level including creating relationships, identifying needs, delivering services and processing feedback.",
    elements: ["Establish contact with customers", "Identify customer needs", "Provide service to customers", "Process customer feedback"],
  },
  { code: "BSBOPS305", title: "Process customer complaints", industry: "BSB", industryName: "Business Services", desc: "Handle complaints from customers.", elements: ["Receive complaints", "Process complaints", "Resolve complaints"] },
  {
    code: "BSBTEC201",
    title: "Use business software applications",
    industry: "BSB",
    industryName: "Business Services",
    desc: "Select and use software and organise electronic information and data.",
    elements: ["Select and use software applications", "Create and use simple spreadsheets", "Organise electronic data"],
  },

  // ─── CHC — Community Services ───
  {
    code: "CHCCCS020",
    title: "Respond effectively to behaviours of concern",
    industry: "CHC",
    industryName: "Community Services",
    desc: "Respond effectively to behaviours of concern in a community services context.",
    elements: ["Identify and assess behaviours of concern", "Plan and implement response", "Evaluate response and report"],
  },
  {
    code: "CHCCCS037",
    title: "Visit and support people in their homes",
    industry: "CHC",
    industryName: "Community Services",
    desc: "Make visits to and support people in their homes in a community services setting.",
    elements: ["Prepare for visit", "Conduct visit", "Follow up on visit"],
  },
  {
    code: "CHCCOM001",
    title: "Provide first point of contact",
    industry: "CHC",
    industryName: "Community Services",
    desc: "Greet and observe people and provide initial information and referrals in a community services context.",
    elements: ["Greet and observe people", "Identify and clarify needs", "Provide information and referral"],
  },
  {
    code: "CHCCOM005",
    title: "Communicate and work in health or community services",
    industry: "CHC",
    industryName: "Community Services",
    desc: "Communicate effectively with people accessing health or community services.",
    elements: ["Communicate with people", "Collaborate with colleagues", "Address communication challenges"],
  },
  {
    code: "CHCDIV001",
    title: "Work with diverse people",
    industry: "CHC",
    industryName: "Community Services",
    desc: "Identify and work with diverse people in a community services context.",
    elements: ["Reflect on own perspectives", "Appreciate diversity", "Communicate with people from diverse backgrounds", "Promote understanding"],
  },
  {
    code: "CHCDIV002",
    title: "Promote Aboriginal and/or Torres Strait Islander cultural safety",
    industry: "CHC",
    industryName: "Community Services",
    desc: "Identify and promote Aboriginal and/or Torres Strait Islander cultural safety in a community services context.",
    elements: ["Identify cultural safety issues", "Model culturally safe practices", "Develop strategies for cultural safety"],
  },
  {
    code: "CHCYTH013",
    title: "Engage respectfully with young people",
    industry: "CHC",
    industryName: "Community Services",
    desc: "Communicate effectively and respectfully with young people in a community services context.",
    elements: ["Communicate with young people", "Establish relationships", "Respond to concerns"],
  },

  // ─── FBP — Food, Beverage & Pharmaceutical ───
  {
    code: "FBPFST4004",
    title: "Perform microbiological tests",
    industry: "FBP",
    industryName: "Food, Beverage & Pharmaceutical",
    desc: "Perform microbiological tests in a food science laboratory.",
    elements: ["Prepare for microbiological testing", "Conduct microbiological tests", "Interpret and report results"],
  },
  {
    code: "FBPFST5005",
    title: "Examine and present food microbiology test results",
    industry: "FBP",
    industryName: "Food, Beverage & Pharmaceutical",
    desc: "Use and apply terms and techniques in food microbiology and examine and present test results.",
    elements: ["Use microbiological terms and techniques", "Examine test results", "Present and report results"],
  },
  {
    code: "FBPFSY3002",
    title: "Participate in a food safety program",
    industry: "FBP",
    industryName: "Food, Beverage & Pharmaceutical",
    desc: "Participate in and support a food safety program in a food processing or food service environment.",
    elements: ["Prepare to participate in food safety program", "Contribute to implementation", "Monitor food safety practices"],
  },
  {
    code: "FBPFSY3003",
    title: "Provide a food safety program service",
    industry: "FBP",
    industryName: "Food, Beverage & Pharmaceutical",
    desc: "Provide a food safety program service to clients in a food processing environment.",
    elements: ["Prepare to provide service", "Assess food safety needs", "Provide food safety advice"],
  },
  {
    code: "FBPFSY4001",
    title: "Maintain and implement a food safety plan",
    industry: "FBP",
    industryName: "Food, Beverage & Pharmaceutical",
    desc: "Maintain and implement an existing food safety plan in a food processing environment.",
    elements: ["Maintain existing food safety plan", "Implement food safety plan", "Monitor and review plan"],
  },
  {
    code: "FBPFSY5001",
    title: "Develop a food safety program",
    industry: "FBP",
    industryName: "Food, Beverage & Pharmaceutical",
    desc: "Develop a food safety program using HACCP principles for a food processing environment.",
    elements: ["Describe the product and its distribution", "Develop a food safety program", "Validate and review program"],
  },
  {
    code: "FBPSUG2024",
    title: "Perform sugar-related testing",
    industry: "FBP",
    industryName: "Food, Beverage & Pharmaceutical",
    desc: "Perform sugar-related testing in a food or pharmaceutical laboratory.",
    elements: ["Prepare for testing", "Conduct sugar tests", "Record and report results"],
  },
  {
    code: "FBPSUG3007",
    title: "Perform tests on sugar and associated products",
    industry: "FBP",
    industryName: "Food, Beverage & Pharmaceutical",
    desc: "Perform tests on sugar and associated products in a food processing environment.",
    elements: ["Prepare samples", "Conduct tests", "Interpret and report results"],
  },
  {
    code: "FBPTEC4009",
    title: "Identify the physical and chemical properties of food",
    industry: "FBP",
    industryName: "Food, Beverage & Pharmaceutical",
    desc: "Apply common physical and chemical properties of food in a food technology context.",
    elements: ["Identify physical properties", "Identify chemical properties", "Apply knowledge to food technology"],
  },

  // ─── HLT — Health ───
  {
    code: "HLTAAP001",
    title: "Recognise healthy body systems",
    industry: "HLT",
    industryName: "Health",
    desc: "Recognise healthy body systems and their interrelationships in a health services context.",
    elements: ["Work with information about healthy body systems", "Recognise body systems and how they work", "Identify interrelationships between body systems"],
  },
  {
    code: "HLTAID009",
    title: "Provide cardiopulmonary resuscitation",
    industry: "HLT",
    industryName: "Health",
    desc: "Perform CPR in line with the Australian Resuscitation Council guidelines.",
    elements: ["Respond to an emergency situation", "Perform CPR", "Communicate details of the incident"],
  },
  {
    code: "HLTCAR004",
    title: "Prepare and conduct an ECG",
    industry: "HLT",
    industryName: "Health",
    desc: "Prepare the patient and conduct an ECG in a clinical setting.",
    elements: ["Prepare ECG machine for use", "Prepare patient for ECG", "Conduct ECG", "Report results"],
  },
  {
    code: "HLTCAR005",
    title: "Prepare and maintain equipment for cardiology procedures",
    industry: "HLT",
    industryName: "Health",
    desc: "Prepare equipment for cardiology procedures and maintain its condition.",
    elements: ["Prepare equipment for procedures", "Maintain cardiology equipment", "Report faults or problems"],
  },
  {
    code: "HLTHPS001",
    title: "Comply with infection prevention and control policies and procedures",
    industry: "HLT",
    industryName: "Health",
    desc: "Comply with infection prevention and control policies and procedures in a health setting.",
    elements: ["Follow standard and transmission-based precautions", "Identify infection risks", "Respond to infection risks"],
  },
  {
    code: "HLTHPS002",
    title: "Prepare and maintain environments, instruments and equipment for clinical procedures",
    industry: "HLT",
    industryName: "Health",
    desc: "Prepare clinical environments, instruments and equipment for clinical procedures.",
    elements: ["Prepare environment", "Prepare instruments and equipment", "Maintain instruments and equipment"],
  },
  {
    code: "HLTHPS011",
    title: "Assist with clinical measurements",
    industry: "HLT",
    industryName: "Health",
    desc: "Assist with clinical measurement procedures in a health services context.",
    elements: ["Prepare for clinical measurements", "Assist with measurements", "Report results"],
  },
  {
    code: "HLTPAT008",
    title: "Collect pathology specimens - anatomical",
    industry: "HLT",
    industryName: "Health",
    desc: "Collect anatomical pathology specimens from patients.",
    elements: ["Confirm collection requirements", "Prepare patient", "Collect specimens", "Process and label specimens"],
  },
  {
    code: "HLTPAT009",
    title: "Confirm pathology collection requirements and prepare patient",
    industry: "HLT",
    industryName: "Health",
    desc: "Confirm pathology collection requirements and prepare the patient for collection.",
    elements: ["Confirm collection requirements", "Prepare patient for collection", "Document collection details"],
  },
  {
    code: "HLTPAT010",
    title: "Perform standard phlebotomy",
    industry: "HLT",
    industryName: "Health",
    desc: "Perform standard phlebotomy procedures to collect venous blood samples.",
    elements: ["Prepare for phlebotomy", "Collect venous blood", "Process samples", "Manage adverse events"],
  },
  {
    code: "HLTPAT011",
    title: "Receive and sort pathology specimens",
    industry: "HLT",
    industryName: "Health",
    desc: "Receive, sort and process pathology specimens in a laboratory.",
    elements: ["Receive specimens", "Sort and label specimens", "Process specimens", "Manage non-conforming specimens"],
  },
  {
    code: "HLTPAT012",
    title: "Prepare patients for capillary blood collection",
    industry: "HLT",
    industryName: "Health",
    desc: "Prepare patients for capillary blood collection procedures.",
    elements: ["Greet client and confirm requirements", "Prepare client for collection", "Collect capillary blood", "Process and label samples"],
  },
  {
    code: "HLTPAT013",
    title: "Collect venous blood samples using a vacuum collection system",
    industry: "HLT",
    industryName: "Health",
    desc: "Collect venous blood samples from patients using a vacuum collection system.",
    elements: ["Prepare to collect venous blood", "Collect venous blood", "Process samples", "Complete documentation"],
  },
  {
    code: "HLTPAT014",
    title: "Collect pathology specimens from patients with special needs",
    industry: "HLT",
    industryName: "Health",
    desc: "Collect pathology specimens from patients with special collection needs.",
    elements: ["Identify special collection requirements", "Prepare patient", "Collect specimens", "Process and document collection"],
  },
  {
    code: "HLTWHS001",
    title: "Participate in workplace health and safety",
    industry: "HLT",
    industryName: "Health",
    desc: "Follow safe work practices for direct client care in a health setting.",
    elements: ["Follow safe work practices", "Contribute to workplace safety", "Participate in WHS consultative processes"],
  },
  {
    code: "HLTWHS006",
    title: "Manage personal stressors in the work environment",
    industry: "HLT",
    industryName: "Health",
    desc: "Identify and manage personal stressors in the work environment in a health services context.",
    elements: ["Identify personal stressors", "Develop strategies to manage personal stressors", "Seek support when required"],
  },

  // ─── MSL — Laboratory Operations ───
  {
    code: "MSL904003",
    title: "Calibrate measuring equipment",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Calibrate measuring equipment in a laboratory or field environment.",
    elements: ["Prepare for calibration", "Calibrate measuring equipment", "Record calibration results"],
  },
  {
    code: "MSL905004",
    title: "Recognise and respond to deviation from experimental procedure",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Recognise and respond to deviation from experimental procedure in a laboratory or field environment.",
    elements: ["Identify deviations from procedure", "Assess impact of deviation", "Respond to deviation and document"],
  },
  {
    code: "MSL905005",
    title: "Create or modify laboratory procedures",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Create or modify laboratory procedures to meet operational requirements.",
    elements: ["Identify need for new or modified procedure", "Develop procedure", "Review and validate procedure"],
  },
  {
    code: "MSL912002",
    title: "Work within a quality assurance framework",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Work within a quality assurance framework in a laboratory or field environment.",
    elements: ["Comply with quality assurance frameworks", "Maintain records", "Participate in quality improvement"],
  },
  {
    code: "MSL913004",
    title: "Plan and organise a personal work program",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Plan and organise a personal work program in a laboratory or field environment.",
    elements: ["Plan work activities", "Organise activities", "Review work program"],
  },
  {
    code: "MSL914002",
    title: "Manage the maintenance of laboratory and field equipment",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Manage the maintenance of laboratory and field equipment.",
    elements: ["Develop maintenance schedule", "Implement maintenance program", "Monitor and review maintenance"],
  },
  {
    code: "MSL915003",
    title: "Respond to and manage a chemical spill",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Respond to and manage a chemical spill in a laboratory or field environment.",
    elements: ["Assess the information", "Respond to the spill", "Review and report on response"],
  },
  {
    code: "MSL915004",
    title: "Schedule and coordinate laboratory or field activities",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Schedule and coordinate laboratory or field activities to meet operational requirements.",
    elements: ["Determine work and laboratory requirements", "Schedule activities", "Coordinate activities and monitor progress"],
  },
  {
    code: "MSL916011",
    title: "Recognise structural features of chemical compounds",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Recognise structural features of chemical compounds from their names and formulae.",
    elements: ["Identify classes of chemical compounds", "Recognise structural features", "Apply knowledge to laboratory practice"],
  },
  {
    code: "MSL916012",
    title: "Develop and manage work health and safety systems",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Develop and manage work health and safety systems in a laboratory or field environment.",
    elements: ["Develop WHS systems", "Implement WHS systems", "Monitor and review WHS systems"],
  },
  {
    code: "MSL916013",
    title: "Monitor and direct the implementation of safe practices",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Monitor and direct the implementation of safe practices in a laboratory or field environment.",
    elements: ["Monitor safe work practices", "Direct work activities", "Review and report on safety"],
  },
  {
    code: "MSL916014",
    title: "Take responsibility for workplace health and safety",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Take responsibility for own actions and workplace health and safety in a laboratory or field environment.",
    elements: ["Take responsibility for WHS", "Contribute to WHS management", "Respond to WHS issues"],
  },
  {
    code: "MSL916015",
    title: "Interpret and apply compliance requirements",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Interpret and apply compliance requirements in a laboratory or field environment.",
    elements: ["Identify compliance requirements", "Implement compliance requirements", "Monitor and review compliance"],
  },
  { code: "MSL922002", title: "Record and present data", industry: "MSL", industryName: "Laboratory Operations", desc: "Record and present data from laboratory or field activities.", elements: ["Record data", "Check data", "Present data"] },
  {
    code: "MSL924005",
    title: "Retrieve data and information from laboratory information systems",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Retrieve data and information from laboratory information systems.",
    elements: ["Retrieve and verify data", "Present retrieved data", "Identify data discrepancies"],
  },
  {
    code: "MSL924006",
    title: "Use enterprise/laboratory information systems",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Use enterprise and laboratory information systems for laboratory activities.",
    elements: ["Access and use laboratory information systems", "Enter and retrieve data", "Generate reports"],
  },
  {
    code: "MSL925005",
    title: "Use computers for scientific purposes",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Use computers for scientific data management and communication purposes.",
    elements: ["Use computer hardware and software", "Process scientific data", "Communicate using computers"],
  },
  {
    code: "MSL925006",
    title: "Perform scientific calculations",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Perform scientific calculations for laboratory or field work.",
    elements: ["Identify calculation requirements", "Perform calculations", "Check and report results"],
  },
  {
    code: "MSL933005",
    title: "Clean and prepare sampling and testing equipment",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Clean and prepare sampling and testing equipment in a laboratory or field environment.",
    elements: ["Plan for cleaning and preparation", "Clean equipment", "Prepare equipment for use"],
  },
  {
    code: "MSL933007",
    title: "Monitor routine and non-routine inputs",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Monitor routine and non-routine inputs into laboratory processes.",
    elements: ["Monitor routine input", "Monitor non-routine input", "Report monitoring results"],
  },
  {
    code: "MSL933008",
    title: "Perform routine laboratory procedures",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Perform routine laboratory procedures using established methods.",
    elements: ["Prepare for routine procedures", "Perform routine procedures", "Report results"],
  },
  {
    code: "MSL933009",
    title: "Apply quality procedures in a laboratory or field environment",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Apply quality procedures in a laboratory or field environment.",
    elements: ["Apply quality procedures", "Monitor quality", "Identify and report non-conformances"],
  },
  {
    code: "MSL934008",
    title: "Check the performance of instrumentation and test equipment",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Check the performance of instrumentation and test equipment in a laboratory environment.",
    elements: ["Check instrument performance", "Identify and report problems", "Document checks"],
  },
  {
    code: "MSL934009",
    title: "Use quality control procedures to maintain test data integrity",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Use quality control procedures to satisfy quality requirements and maintain data integrity.",
    elements: ["Satisfy quality requirements in test processes", "Apply statistical quality control", "Report quality control results"],
  },
  {
    code: "MSL934010",
    title: "Order, maintain and store laboratory stocks and supplies",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Order, maintain and store laboratory stocks and supplies.",
    elements: ["Maintain and store stocks", "Order stocks and supplies", "Manage stock records"],
  },
  {
    code: "MSL935005",
    title: "Critically evaluate and apply information from scientific literature",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Critically evaluate and apply information from scientific literature.",
    elements: ["Identify and access literature", "Evaluate accuracy of information", "Apply information"],
  },
  {
    code: "MSL935006",
    title: "Assist in the acquisition of biological specimens",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Assist in the acquisition of biological specimens for laboratory analysis.",
    elements: ["Prepare for specimen acquisition", "Acquire specimens", "Process and store specimens"],
  },
  {
    code: "MSL935008",
    title: "Analyse a sample using spectroscopic techniques",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Analyse a sample using spectroscopic techniques.",
    elements: ["Prepare for spectroscopic analysis", "Perform spectroscopic analysis", "Interpret and report results"],
  },
  {
    code: "MSL936005",
    title: "Take representative samples from a static material",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Take representative samples from a static material for laboratory analysis.",
    elements: ["Prepare for sampling", "Take samples", "Document sampling"],
  },
  {
    code: "MSL936006",
    title: "Prepare for and conduct audits",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Prepare for and conduct audits of laboratory quality systems.",
    elements: ["Prepare for audit", "Conduct audit", "Report audit findings"],
  },
  {
    code: "MSL943003",
    title: "Safely store, handle and dispose of laboratory chemicals and substances",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Safely store, handle and dispose of chemicals and substances in a laboratory.",
    elements: ["Identify chemical hazards", "Store and handle chemicals safely", "Dispose of chemicals safely"],
  },
  {
    code: "MSL943004",
    title: "Follow work health and safety procedures in a laboratory or field environment",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Follow work health and safety procedures in a laboratory or field environment.",
    elements: ["Follow WHS procedures", "Report hazards", "Respond to WHS incidents"],
  },
  {
    code: "MSL944002",
    title: "Monitor and safely use hazardous chemicals in the laboratory",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Monitor and safely use hazardous chemicals in the laboratory environment.",
    elements: ["Assess chemical hazards", "Monitor use of hazardous chemicals", "Manage chemical incidents"],
  },
  {
    code: "MSL946003",
    title: "Implement and monitor environmentally sustainable work practices",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Implement and monitor environmentally sustainable work practices in a laboratory.",
    elements: ["Identify sustainability requirements", "Implement sustainable practices", "Monitor and improve sustainability"],
  },
  {
    code: "MSL952003",
    title: "Collect samples from a natural or managed environment",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Collect samples from a natural or managed environment for laboratory analysis.",
    elements: ["Prepare for sampling", "Collect samples", "Preserve and transport samples"],
  },
  {
    code: "MSL952004",
    title: "Pick up and prepare pathology specimens for transport",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Pick up and prepare pathology specimens for transport to the laboratory.",
    elements: ["Prepare for pickup", "Collect and package specimens", "Transport specimens"],
  },
  {
    code: "MSL953004",
    title: "Operate a robotic sample processing system",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Operate a robotic sample processing system in a laboratory environment.",
    elements: ["Prepare robotic system", "Operate system", "Troubleshoot system problems"],
  },
  {
    code: "MSL953005",
    title: "Log samples, specimens and associated documentation",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Log samples, specimens and associated documentation in a laboratory information system.",
    elements: ["Receive and check samples", "Log samples and documentation", "Manage non-conforming samples"],
  },
  {
    code: "MSL954005",
    title: "Reduce given samples to laboratory test portions",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Reduce given samples to laboratory test portions for analysis.",
    elements: ["Prepare for sample reduction", "Reduce samples", "Document sample reduction"],
  },
  {
    code: "MSL954006",
    title: "Recognise and respond to emergency situations in pathology",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Recognise and respond to emergency situations involving patients in a pathology setting.",
    elements: ["Identify emergency situations", "Respond to emergencies", "Document and report emergencies"],
  },
  {
    code: "MSL954007",
    title: "Obtain a range of specimens for pathological examination",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Obtain a range of specimens for pathological examination using appropriate techniques.",
    elements: ["Confirm collection requirements", "Obtain specimens", "Process and label specimens"],
  },
  {
    code: "MSL972002",
    title: "Take direct measurements",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Take direct measurements in a laboratory or field environment.",
    elements: ["Prepare for measurements", "Take measurements", "Record and report measurements"],
  },
  {
    code: "MSL973015",
    title: "Prepare microbiological media and reagents",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Prepare microbiological media and reagents for laboratory use.",
    elements: ["Prepare media and reagents", "Check media and reagent quality", "Store media and reagents"],
  },
  {
    code: "MSL973017",
    title: "Perform tasks associated with fieldwork",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Perform tasks associated with fieldwork in a scientific environment.",
    elements: ["Prepare for fieldwork", "Assist with fieldwork", "Complete fieldwork documentation"],
  },
  {
    code: "MSL973018",
    title: "Prepare trial batch of a food product",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Prepare a trial batch of a food product in a laboratory or pilot plant environment.",
    elements: ["Prepare trial batch", "Monitor production", "Evaluate and report on trial batch"],
  },
  {
    code: "MSL973021",
    title: "Conduct in field-based environmental monitoring",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Conduct in field-based environmental monitoring activities.",
    elements: ["Prepare for monitoring", "Conduct field-based monitoring", "Record and report results"],
  },
  {
    code: "MSL973022",
    title: "Conduct laboratory-based environmental analysis",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Conduct laboratory-based environmental analysis using standard methods.",
    elements: ["Prepare for analysis", "Conduct analysis", "Interpret and report results"],
  },
  {
    code: "MSL973023",
    title: "Follow shift work procedures",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Follow shift work procedures in a laboratory environment.",
    elements: ["Prepare for shift", "Conduct shift work", "Complete shift handover"],
  },
  {
    code: "MSL973024",
    title: "Prepare for on-site environmental sampling",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Prepare for on-site environmental sampling activities.",
    elements: ["Plan sampling activities", "Prepare equipment", "Travel to sampling site"],
  },
  {
    code: "MSL973025",
    title: "Prepare reagents, standard solutions and culture media",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Prepare reagents, standard solutions and culture media for laboratory use.",
    elements: ["Interpret test requirements", "Prepare solutions and media", "Check and store preparations"],
  },
  {
    code: "MSL973026",
    title: "Make up solutions of defined concentration",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Make up solutions of defined concentration for laboratory use.",
    elements: ["Identify solution requirements", "Make up solutions", "Check and label solutions"],
  },
  {
    code: "MSL973027",
    title: "Perform gravimetric analysis",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Perform gravimetric analysis in a laboratory environment.",
    elements: ["Prepare for gravimetric analysis", "Perform analysis", "Calculate and report results"],
  },
  {
    code: "MSL973028",
    title: "Set up a light microscope",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Set up a light microscope for examination of specimens.",
    elements: ["Prepare microscope for use", "Set up for examination", "Maintain microscope"],
  },
  {
    code: "MSL973029",
    title: "Perform basic microbiology tests",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Perform basic microbiology tests in a laboratory environment.",
    elements: ["Prepare for microbiology testing", "Perform tests", "Process and report results"],
  },
  {
    code: "MSL974016",
    title: "Interpret and report chemical test results",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Interpret and report chemical test results in a laboratory environment.",
    elements: ["Interpret test results", "Evaluate results", "Report results"],
  },
  {
    code: "MSL974018",
    title: "Prepare for and conduct chromatographic analysis",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Prepare for and conduct chromatographic analysis of samples.",
    elements: ["Prepare for chromatographic analysis", "Conduct analysis", "Interpret and report results"],
  },
  {
    code: "MSL974022",
    title: "Organise and manage fieldwork activities",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Organise and manage fieldwork activities in a scientific environment.",
    elements: ["Plan fieldwork", "Organise fieldwork", "Manage fieldwork activities"],
  },
  {
    code: "MSL974023",
    title: "Capture and record field data",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Capture and record field data during environmental or scientific fieldwork.",
    elements: ["Prepare for data capture", "Capture and record data", "Report field data"],
  },
  {
    code: "MSL974026",
    title: "Schedule and conduct test analyses",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Schedule and conduct test analyses in a laboratory environment.",
    elements: ["Schedule test analyses", "Conduct analyses", "Report results"],
  },
  {
    code: "MSL974028",
    title: "Classify soils for engineering and construction",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Classify soils for engineering and construction investigations.",
    elements: ["Classify soil samples", "Conduct soil tests", "Report classification results"],
  },
  {
    code: "MSL974029",
    title: "Operate a spectrophotometer for chemical analysis",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Operate a spectrophotometer for chemical analysis in a laboratory environment.",
    elements: ["Prepare spectrophotometer", "Conduct spectrophotometric analysis", "Report results"],
  },
  {
    code: "MSL974031",
    title: "Prepare, standardise and use volumetric solutions",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Prepare, standardise and use volumetric solutions for laboratory analysis.",
    elements: ["Prepare volumetric solutions", "Standardise solutions", "Use solutions for analysis"],
  },
  {
    code: "MSL974032",
    title: "Interpret and apply spectral data",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Interpret and apply spectral data from spectroscopic analysis.",
    elements: ["Interpret spectral data", "Apply data interpretation", "Report findings"],
  },
  {
    code: "MSL974033",
    title: "Interpret food chemistry test results",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Interpret food chemistry test results in a food laboratory environment.",
    elements: ["Interpret test results", "Evaluate results against specifications", "Report results"],
  },
  {
    code: "MSL974034",
    title: "Interpret work instructions for chemistry testing",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Interpret work instructions for chemistry testing in a laboratory environment.",
    elements: ["Interpret and apply work instructions", "Apply instructions to chemistry testing", "Report any discrepancies"],
  },
  {
    code: "MSL974035",
    title: "Prepare and operate an electron microscope",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Prepare and operate an electron microscope for specimen examination.",
    elements: ["Prepare electron microscope", "Operate microscope", "Process and report results"],
  },
  {
    code: "MSL974036",
    title: "Complete pre-analytical processes for pathology",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Complete pre-analytical processes for pathology specimens.",
    elements: ["Receive specimens", "Complete pre-analytical processes", "Forward specimens for analysis"],
  },
  {
    code: "MSL974037",
    title: "Triage and prioritise pathology specimens",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Triage and prioritise pathology specimens for analysis.",
    elements: ["Receive and assess specimens", "Triage and prioritise specimens", "Document and report triaging"],
  },
  {
    code: "MSL974038",
    title: "Process and prepare tissue specimens",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Process and prepare tissue specimens for pathological examination.",
    elements: ["Receive tissue specimens", "Process specimens", "Prepare specimens for examination"],
  },
  {
    code: "MSL975032",
    title: "Work closely with a medical practitioner or specialist",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Work closely with a medical practitioner or specialist in a pathology environment.",
    elements: ["Prepare for specialist consultation", "Support specialist activities", "Document activities"],
  },
  {
    code: "MSL975038",
    title: "Set up and calibrate analytical instruments",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Set up and calibrate analytical instruments for laboratory use.",
    elements: ["Set up instruments", "Calibrate instruments", "Document calibration"],
  },
  {
    code: "MSL975041",
    title: "Safely extract ore samples by fire assay",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Safely extract ore samples by fire assay for laboratory analysis.",
    elements: ["Prepare for fire assay", "Conduct fire assay", "Process results"],
  },
  {
    code: "MSL975042",
    title: "Design and conduct field-based surveys",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Design and conduct field-based environmental or scientific surveys.",
    elements: ["Design surveys", "Conduct field surveys", "Analyse and report survey results"],
  },
  {
    code: "MSL975043",
    title: "Perform a site assessment",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Perform a site assessment for environmental or scientific purposes.",
    elements: ["Prepare for site assessment", "Conduct site assessment", "Report assessment findings"],
  },
  {
    code: "MSL975044",
    title: "Prepare and interpret test results for regulatory compliance",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Prepare and interpret test results for regulatory compliance purposes.",
    elements: ["Prepare test results", "Interpret results", "Report compliance status"],
  },
  {
    code: "MSL975051",
    title: "Supervise and conduct sampling activities",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Supervise and conduct sampling activities in a laboratory or field environment.",
    elements: ["Plan sampling activities", "Supervise sampling", "Conduct and document sampling"],
  },
  {
    code: "MSL975052",
    title: "Locate, record and collect biological specimens",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Locate, record and collect biological specimens from natural environments.",
    elements: ["Prepare for collection", "Locate and record specimens", "Collect and process specimens"],
  },
  {
    code: "MSL975055",
    title: "Classify collected organisms",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Classify collected organisms using appropriate taxonomic methods.",
    elements: ["Prepare for classification", "Classify organisms", "Document classification results"],
  },
  {
    code: "MSL975056",
    title: "Perform tests related to disease diagnosis",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Perform tests related to disease diagnosis in a pathology laboratory.",
    elements: ["Prepare for diagnostic testing", "Perform diagnostic tests", "Interpret and report results"],
  },
  {
    code: "MSL975057",
    title: "Perform tests on specimens for infectious disease",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Perform tests on specimens for infectious disease diagnosis.",
    elements: ["Prepare for testing", "Perform infectious disease tests", "Interpret and report results"],
  },
  {
    code: "MSL975058",
    title: "Perform tests on blood and blood products",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Perform tests on blood and blood products in a pathology laboratory.",
    elements: ["Prepare for blood testing", "Perform blood tests", "Interpret and report results"],
  },
  {
    code: "MSL975059",
    title: "Supervise and conduct on-site environmental sampling",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Supervise and conduct on-site environmental sampling activities.",
    elements: ["Plan on-site sampling", "Supervise sampling activities", "Document and report sampling"],
  },
  {
    code: "MSL975060",
    title: "Prepare, separate and identify components of samples",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Prepare, separate and identify the components of samples for analysis.",
    elements: ["Prepare samples", "Separate sample components", "Identify and report components"],
  },
  {
    code: "MSL975061",
    title: "Isolate, identify and type microorganisms",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Isolate, identify and type microorganisms for laboratory analysis.",
    elements: ["Isolate microorganisms", "Identify and type microorganisms", "Report findings"],
  },
  {
    code: "MSL975062",
    title: "Contribute to environmental surveys and assessments",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Contribute to environmental surveys and assessments in a scientific environment.",
    elements: ["Prepare for surveys", "Contribute to survey activities", "Report contributions"],
  },
  {
    code: "MSL975063",
    title: "Determine structural features of organic compounds",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Determine structural features of organic compounds using spectroscopic analysis.",
    elements: ["Identify analysis requirements", "Conduct spectroscopic analysis", "Interpret and report results"],
  },
  {
    code: "MSL975064",
    title: "Perform tests on biological materials from pharmaceutical goods",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Perform tests on biological materials from pharmaceutical goods and other products.",
    elements: ["Prepare for testing", "Perform biological tests", "Interpret and report results"],
  },
  {
    code: "MSL975065",
    title: "Analyse samples for volatile organic compounds",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Analyse samples for volatile and semi-volatile organic compounds.",
    elements: ["Prepare samples for analysis", "Conduct analysis", "Interpret and report results"],
  },
  {
    code: "MSL975066",
    title: "Analyse samples for semi-volatile organic compounds",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Analyse samples for semi-volatile organic compounds using appropriate techniques.",
    elements: ["Prepare samples", "Conduct analysis", "Report results"],
  },
  {
    code: "MSL975067",
    title: "Isolate and identify organic compounds by chromatography",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Isolate and identify organic compounds using chromatographic techniques.",
    elements: ["Prepare for chromatography", "Conduct chromatographic analysis", "Interpret and report results"],
  },
  {
    code: "MSL975068",
    title: "Analyse samples by atomic absorption spectrometry",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Analyse samples by atomic absorption spectrometry.",
    elements: ["Prepare for atomic absorption analysis", "Conduct analysis", "Interpret and report results"],
  },
  {
    code: "MSL975069",
    title: "Analyse samples by inductively coupled plasma spectrometry",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Analyse samples by inductively coupled plasma spectrometry.",
    elements: ["Prepare for ICP analysis", "Conduct analysis", "Interpret and report results"],
  },
  {
    code: "MSL975070",
    title: "Analyse samples by ion chromatography",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Analyse samples by ion chromatography.",
    elements: ["Prepare for ion chromatography", "Conduct analysis", "Interpret and report results"],
  },
  {
    code: "MSL975071",
    title: "Analyse samples by thermal analysis",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Analyse samples by thermal analysis techniques.",
    elements: ["Prepare for thermal analysis", "Conduct analysis", "Interpret and report results"],
  },
  {
    code: "MSL975072",
    title: "Analyse samples by X-ray diffraction",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Analyse samples by X-ray diffraction techniques.",
    elements: ["Prepare for X-ray diffraction", "Conduct analysis", "Interpret and report results"],
  },
  {
    code: "MSL975073",
    title: "Prepare for and conduct immunological tests",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Prepare for and conduct immunological tests in a laboratory environment.",
    elements: ["Prepare for immunological testing", "Conduct tests", "Interpret and report results"],
  },
  {
    code: "MSL976006",
    title: "Evaluate and validate analytical methods",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Evaluate and validate analytical methods for laboratory use.",
    elements: ["Plan method evaluation", "Conduct evaluation", "Report validation findings"],
  },
  {
    code: "MSL977009",
    title: "Validate test methods",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Validate test methods for laboratory use.",
    elements: ["Confirm validation requirements", "Conduct validation", "Report validation results"],
  },
  {
    code: "MSL977010",
    title: "Evaluate a laboratory quality management system",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Evaluate a laboratory quality management system against standards.",
    elements: ["Plan evaluation", "Conduct evaluation", "Report findings and recommendations"],
  },
  {
    code: "MSL977011",
    title: "Apply statistical quality control techniques",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Apply statistical quality control techniques in a laboratory environment.",
    elements: ["Identify statistical techniques", "Apply statistical techniques", "Interpret and report results"],
  },
  {
    code: "MSL977012",
    title: "Develop or revise a test method",
    industry: "MSL",
    industryName: "Laboratory Operations",
    desc: "Develop or revise a test method for laboratory use.",
    elements: ["Plan test method development", "Develop or revise test method", "Validate and document test method"],
  },

  // ─── MSM — Manufacturing ───
  {
    code: "MSMENV272",
    title: "Identify and assess environmental and energy impacts",
    industry: "MSM",
    industryName: "Manufacturing",
    desc: "Identify and assess environmental and energy impacts of manufacturing work activities.",
    elements: ["Identify environmental impacts", "Assess energy impacts", "Report findings"],
  },
  {
    code: "MSMENV472",
    title: "Investigate energy and environmental impacts and solutions",
    industry: "MSM",
    industryName: "Manufacturing",
    desc: "Investigate energy and environmental impacts and solutions in a manufacturing environment.",
    elements: ["Investigate energy impacts", "Investigate environmental impacts", "Develop and report on solutions"],
  },
  {
    code: "MSMENV672",
    title: "Develop workplace policies and procedures for environmental sustainability",
    industry: "MSM",
    industryName: "Manufacturing",
    desc: "Develop workplace policies and procedures for environmental sustainability in a manufacturing environment.",
    elements: ["Develop environmental policies", "Develop sustainability procedures", "Implement and review policies"],
  },
  {
    code: "MSMSUP301",
    title: "Use HACCP principles",
    industry: "MSM",
    industryName: "Manufacturing",
    desc: "Apply hazard analysis and critical control point (HACCP) principles to the manufacture of food products.",
    elements: ["Prepare to implement HACCP plan", "Implement HACCP plan", "Monitor HACCP plan"],
  },

  // ─── RII — Resources & Infrastructure ───
  {
    code: "RIISTD401",
    title: "Supervise a laboratory",
    industry: "RII",
    industryName: "Resources & Infrastructure",
    desc: "Supervise laboratory operations and staff in a resources and infrastructure environment.",
    elements: ["Prepare to supervise laboratory", "Supervise laboratory activities", "Review and report on laboratory operations"],
  },

  // ─── TAE — Training & Education ───
  {
    code: "TAEDEL311",
    title: "Provide work skill instruction",
    industry: "TAE",
    industryName: "Training & Education",
    desc: "Conduct individual and small group work skill instruction using existing support materials.",
    elements: ["Prepare for training delivery", "Deliver work skill training", "Review and report on training delivery"],
  },
];

export const INDUSTRIES = [
  { code: "AMP", name: "Australian Meat Processing" },
  { code: "BSB", name: "Business Services" },
  { code: "CHC", name: "Community Services" },
  { code: "FBP", name: "Food, Beverage & Pharmaceutical" },
  { code: "HLT", name: "Health" },
  { code: "MSL", name: "Laboratory Operations" },
  { code: "MSM", name: "Manufacturing" },
  { code: "RII", name: "Resources & Infrastructure" },
  { code: "TAE", name: "Training & Education" },
];
